version: '3'
services:
  db:
    image: ifilip/db:latest
    ports:
       - "3306:3306"
    restart: always
    build:
      context: .
      dockerfile: mysql/dockerfile.db
    environment:
      - TZ='Europe/Bucharest'
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=0.0.0.0/0.0.0.0
    volumes: 
      - db:/var/lib/msyql/data/
    networks:
      dc-network:
        ipv4_address: 172.18.2.13

  app1:
    image: ifilip/wp:latest
    build:
      context: .
      dockerfile: wordpress/dockerfile.wp
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      dc-network:
        ipv4_address: 172.18.2.11
    
  app2:
    image: ifilip/wp:latest
    build:
      context: .
      dockerfile: wordpress/dockerfile.wp
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      dc-network:
        ipv4_address: 172.18.2.12
  lb:
    image: ifilip/lb:latest
    depends_on:
      - app1
      - app2
    build:
      context: .
      dockerfile: nginx/dockerfile.lb
    ports:
      - 80:80
    networks:
      dc-network:
        ipv4_address: 172.18.2.10

  
  
volumes:
  db:
    driver: local
  wordpress:
    driver: local


networks: 
    dc-network:
        driver: bridge
        ipam: 
            driver: default
            config: 
                - subnet: 172.18.2.0/24