version: '3'
services:
  db:
    image: ifilip/db:latest
    container_name: db
    ports:
       - "3306:3306"
    restart: always
    env_file:
      - .env
    build:
      context: .
    #  dockerfile: mysql/dockerfile.db
    environment:
      - TZ='Europe/Bucharest'
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      #- MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      #- MYSQL_DB=${MYSQL_DB}
      #- MYSQL_USER=${MYSQL_USER}
      #- MYSQL_PASSWORD=${MYSQL_PASSWORD}
      #- MYSQL_ROOT_HOST=0.0.0.0/0.0.0.0
    volumes: 
      - db:/var/lib/msyql/data/

  app1:
    depends_on:
       - db
    image: ifilip/wp:latest
    container_name: app1
    links:
     - db:mysql
    build:
      context: .
      #dockerfile: wordpress/dockerfile.wp
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306

    
  app2:
    depends_on:
      - db
    image: ifilip/wp:latest
    container_name: app2
    links:
     - db:mysql
    build:
      context: .
      #dockerfile: wordpress/dockerfile.wp
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: always
    ports:
      - 8080:80

  lb:
    image: ifilip/lb:latest
    container_name: lb
    depends_on:
      - app1
      - app2
    build:
      context: .
      #dockerfile: nginx/dockerfile.lb
    ports:
      - 80:80
  
volumes:
  db:
    driver: local
  wordpress:
    driver: local
