version: '3'
services:

  app1:
    image: ifilip/wp:latest
    build:
      context: .
      dockerfile: wordpress/dockerfile.wp
    volumes:
      - wordpress:/var/www/html/wordpress
    
  app2:
    image: ifilip/wp:latest
    volumes:
      - wordpress:/var/www/html/wordpress
  
  lb:
    image: ifilip/lb:latest
    depends_on:
      - app1
      - app2
    build:
      context: .
      dockerfile: nginx/dockerfile.lb
    ports:
      - 80:80

  db:
    image: ifilip/db:latest
    ports:
       - "3306:3306"
    restart: always
    build:
      context: .
      dockerfile: mysql/dockerfile.db
    environment:
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes: 
      - db:/var/lib/msyql/data/
  
volumes:
  db:
    driver: local
  wordpress:
    driver: local