name: Wantsome Project 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_push_nginx_docker_images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS 
    - name: Build Nginx image
      run: |
        docker build . --file ./apps/nginx/Dockerfile.lb --tag ${{ secrets.DOCKER_USER }}/lb:latest
    - name: Push Nginx image
      run: docker push ${{ secrets.DOCKER_USER }}/lb:latest

  build_and_push_mysql_docker_images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS 
    - name: Build Mysql image
      run: |
        docker build . --file ./apps/mysql/Dockerfile.db --tag ${{ secrets.DOCKER_USER }}/db:latest
    - name: Push Mysql image
      run: docker push ${{ secrets.DOCKER_USER }}/db:latest
  
  build_and_push_wordpress_docker_images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS 
    - name: Build Wordpress image
      run: |
        docker build . --file ./apps/wordpress/Dockerfile.wp --tag ${{ secrets.DOCKER_USER }}/wp:latest
    - name: Push Wordpress image
      run: docker push ${{ secrets.DOCKER_USER }}/wp:latest

