name: Wantsome Project 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKER_USER }}/lb
        tags: type=raw, value={{date 'YYYYMMDD'}}

    - name: DockerHub Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }} 
        
    - name: Build and Push Nginx image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./apps/nginx/Dockerfile.lb 
        push: true
        tags:  ${{ secrets.DOCKER_USER }}/lb:latest ${{ steps.meta.outputs.tags }}
      #run: docker build . --file ../apps/nginx/Dockerfile.lb --tag ifilip/lb:$(date +%s) --tag ifilip/lb:latest
    #- name: Build the Docker image for Mysql
    #  run: docker build . --file ../../apps/mysql/Dockerfile.db --tag ifilip/db:$(date +%s) --tag ifilip/db:latest
    #- name: Build the Docker image for Wordpress
    #  run: docker build . --file apps/wordpress/Dockerfile.wp --tag ifilip/wp:$(date +%s) --tag ifilip/wp:latest
  
  #push:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: {apare se buton}
  #  - names: Push docker images for nginx on dockerhub.com
  #    run: docker push ...

